server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://106.13.64.74:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
